version: 3

jobs:
  build:
    docker:
      - image: "circleci/node:10.24.0-browsers"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v5-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v5-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
